function createMapBaseTetriminos(){
    tetriminosBase = {
        "Z":{
            color:"#f0823f",
            map:[
            createVector(),
            createVector(-1,-1),
            createVector(0,-1),
            createVector(1,0)
            ]
        },
        "S":{
            color:"#bd374c",
            map:[
            createVector(),
            createVector(1,-1),
            createVector(0,-1),
            createVector(-1,0)
            ]
        },
        "J":{
            color:"#f7f799",
            map:[
            createVector(),
            createVector(-1,0),
            createVector(-1,-1),
            createVector(1,0)
            ]
        },
        "L":{
            color:"#ffe999",
            map:[
            createVector(),
            createVector(-1,0),
            createVector(1,-1),
            createVector(1,0)
            ]
        },
        "T":{
            color:"#c71755",
            map:[
            createVector(),
            createVector(-1,0),
            createVector(1,0),
            createVector(0,-1)
            ]
        },
        "O":{
            color:"#f4324a",
            map:[
            createVector(),
            createVector(-1,0),
            createVector(-1,1),
            createVector(0,1)
            ]
        },
        "Y":{
            color:"#fb9c5a",
            map:[
            createVector(),
            createVector(1,0),
            createVector(0,1),
            createVector(1,-1)
            ]
        },
        "I":{
            color:"#742cbd",
            map:[
            createVector(),
            createVector(0,3),
            createVector(0,2),
            createVector(0,1)
            ]
        },
        "P":{
            color:"#e32f21",
            map:[
            createVector(),
            createVector(-1,0),
            createVector(1,0),
            createVector(2,0)
            ]
        },
    }
   }
